Arguments: 
  /Users/tal/.nvm/versions/node/v19.3.0/bin/node /Users/tal/.nvm/versions/node/v19.3.0/bin/yarn add vite

PATH: 
  /Users/tal/.nvm/versions/node/v19.3.0/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/tal/.nvm/versions/node/v19.3.0/bin

Yarn version: 
  1.22.19

Node version: 
  19.3.0

Platform: 
  darwin x64

Trace: 
  Error: https://npm.xesv5.com/vite: Request "https://npm.xesv5.com/vite" returned a 403
      at params.callback [as _callback] (/Users/tal/.nvm/versions/node/v19.3.0/lib/node_modules/yarn/lib/cli.js:66154:18)
      at self.callback (/Users/tal/.nvm/versions/node/v19.3.0/lib/node_modules/yarn/lib/cli.js:140890:22)
      at Request.emit (node:events:513:28)
      at Request.<anonymous> (/Users/tal/.nvm/versions/node/v19.3.0/lib/node_modules/yarn/lib/cli.js:141862:10)
      at Request.emit (node:events:513:28)
      at IncomingMessage.<anonymous> (/Users/tal/.nvm/versions/node/v19.3.0/lib/node_modules/yarn/lib/cli.js:141784:12)
      at Object.onceWrapper (node:events:627:28)
      at IncomingMessage.emit (node:events:525:35)
      at endReadableNT (node:internal/streams/readable:1359:12)
      at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

npm manifest: 
  {
    "name": "test",
    "version": "1.0.0",
    "main": "index.js",
    "license": "MIT"
  }

yarn manifest: 
  No manifest

Lockfile: 
  No lockfile
